README.md, compiler/noirc_driver/src/lib.rs, compiler/wasm/src/compile.rs, compiler/wasm/src/compile_new.rs, tooling/nargo/src/ops/compile.rs, tooling/nargo_cli/build.rs, tooling/nargo_cli/src/cli/compile_cmd.rs, tooling/nargo_cli/src/cli/debug_cmd.rs, tooling/nargo_cli/src/cli/prove_cmd.rs, tooling/nargo_cli/src/cli/verify_cmd.rs
feat: Remove `--use-plonky2-backend-experimental` flag
Now that `nargo prove` has no other implementation than ours, we remove
the flag to simplify things.
Note that the majority of `nargo` commands should still be able to skip
compilation of PLONKY2 code, since our backend is not complete and does
not support all possible operations (especially unrestricted ones).
That's why an additional argument is added to some compilation commands
that are reused throughout the system.
Also, README.md is updated to quit the yapping and plainly say how our
fork differs from upstream Noir.
Testing:
`cargo test` reports no failures;
`cd test_programs/plonky2_prove_success/zk_dungeon && nargo prove &&
nargo verify` reports no errors, so it succeeds;
Coda task: …
=> feat: Remove `--use-plonky2-backend-experimental` flag

compiler/noirc_evaluator/src/errors.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/circuit.rs
Verify that the public inputs from the deserialized proof indeed match the expected public inputs from the Prover.toml file
=> feat(plonky2): Check the public inputs when verifying a proof

test_programs/plonky2_trace/1_mul, tooling/nargo_cli/build.rs
This scaffolding allows the additions of tests for `nargo trace` in the same vein as tests are added for other nargo commands.
To check locally what this PR does, checkout the repo and run
`cargo test plonky2_trace`
It should result in a single test running successfully.
To convince yourself that the test is real, try changing the info message printed in `tooling/tracer/src/lib.rs:117` and running the test again.
Note: there is no actual tracing logic yet, but this will be added in
following commits.
=> feat(tracing): Add scaffolding for tracing tests

tooling/tracer/src/lib.rs
This commit has no functional changes.
To verify, run `cargo test plonky2_trace`, which should still pass (the
test is not touched by this commit).
Changes:
- `next_into` is renamed to `step_debugger`; a doccomment is added
- the function is simplified: it now performs less matching
- `validate_in_progress`, a remnant from the debugger REPL is no longer
needed, so it's removed
- `handle_debug_command_result`: ditto
- the field `context` is renamed to `debug_context`, to reduce
potential confusion
- the complexity (matching of the debugger result) is lifted into the
`trace_circuit` function
Next commit to start adding more logic to `step_debugger`.
=> feat(tracing): More structural cleanup

compiler/noirc_evaluator/src/ssa.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/console_asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/div_generator.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
Introduces a plonky2 "assembler writer" and implements display of a large number of plonky2 operations when the '--show-plonky2' command line option is used. Not all operations are shown, yet. The rest are going to be implemented in future commits.
=> feat(plonky2): Partial implementation of '--show-plonky2'

test_programs/plonky2_trace/1_mul/expected_trace.json, tooling/tracer/src/lib.rs
This commit just outlines some logic into the
`get_current_line_and_filepath` function, to keep the body of
`step_debugger` fitting on a single screen.
There is no functional change: the test still passes:
```
cargo test plonky2_trace
```
=> feat(tracing): Outline `get_current_line_and_filepath`

compiler/noirc_evaluator/src/ssa/plonky2_gen/asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/console_asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/intrinsics/sha256.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
This makes the operations generated by the PLONKY2 sha256 intrinsic code generator visible via the '--show-plonky2' command line option. Additionally, the following operations were introduced to the AsmWriter:
add_virtual_bool_target_unsafe
constant_u32
add_u32
split_le_base
=> feat(plonky2): Converted the sha256 intrinsic codegen to use the new AsmWriter

compiler/noirc_evaluator/src/ssa/plonky2_gen/asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/console_asm_writer.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/div_generator.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
After these changes, all plonky2 calls should (in theory) be printed to the screen by the '--show-plonky2' command line option.
=> feat(plonky2): converted the remaining parts of the PLONKY2 code generator to use the AsmWriter

compiler/noirc_driver/src/lib.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/config.rs, compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs, tooling/nargo_cli/src/cli/compile_cmd.rs, tooling/nargo_cli/src/cli/verify_cmd.rs, tooling/noirc_abi/src/lib.rs
Upstream consistently applies 'cargo fmt' to all their commits (they run 'cargo fmt --check' in their CI and expect empty output). This applies the 'cargo fmt' formatting fixes to our code as well.
=> chore: applied 'cargo fmt'. No functional changes.

test_programs/execution_success/simple_unconstrained/Nargo.toml, test_programs/execution_success/simple_unconstrained/Prover.toml, test_programs/execution_success/simple_unconstrained/src/main.nr
The purpose of this test is to show a minimal useful program that makes use of the `unconstrained` capabilities of Noir and to show that the `nargo` tool is capable of executing it and performing the associated assert.
Note that the `unconstrained` code is, unsurprisingly, not included in the constraint system, so it is not part of the ZK proof/verification. It is just a utility that allows programs to get around performance limitations of the arithmetic circuit paradigm. Modern zkVMs provide a way to include such code in the proof as well, but these are in even earlier stage of development at the moment.
To run test:
```
cargo test simple_unconstrained
```
=> test(unconstrained): add simple test

tooling/nargo_cli/build.rs
Skip test dirs that are empty, or contains build artifacts from a previously existing test, that has been deleted.
=> refactor(tests): Ignore partially removed tests

Cargo.lock
When the `format_trace` package was added, the effect on Cargo.lock was not added to the commit, so this commit fixes that.
Also, it contains some version bumps as a drive-by.
=> chore(Cargo.lock): update with new package

testing/format_trace/src/main.rs
Added unit tests for format tracer. They are located in the main.rs file. They are testing the functions which are formatting the json input. Those functions are located in prettify.rs.
=> test(tracing): Add unit tests for trace formatter

compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
The messages "unsupported indexing array with" updated to include in the message text whether it's doing an array get or an array set operation.
=> feat(plonky2): updated error messages for unsupported array operation

tooling/nargo_cli/src/cli/fv_cmd.rs, tooling/nargo_cli/src/cli/mod.rs
Added a command for the formal verification tool which is being worked on. Currently the command `nargo fv` prints a message for the user and returns a generic cli error.
=> Nargo command for formal verifier tool

compiler/noirc_frontend/src/lexer/lexer.rs, compiler/noirc_frontend/src/lexer/token.rs
Added tokens to the lexer to process our formal verification annotations, which follow the syntax of an attribute. Also added a unit test.
=> chore(fv): integrate annotation tokens into lexer

compiler/noirc_frontend/src/lexer/lexer.rs, compiler/noirc_frontend/src/lexer/token.rs
Made separate tokens for formal verification attributes because they need more complex lexing and parsing compared to the built-in attributes.
Also added lexing logic for them and added support for having new lines in the expression body of a formal verification attribute.
For more details please take a look at the added unit tests.
Some explanation for the code: I've added a flag in the Lexer struct which serves as an indicator if we are currently tokenizing a formal verification attribute or not. If we are tokenizing a formal verification attribute we must tokenize the new lines as the token EOL because they will serve us as an indicator where the attribute ends during the parsing process.
=> feat(fv): add lexing for fv annotations

compiler/noirc_frontend/src/lexer/token.rs, compiler/noirc_frontend/src/parser/errors.rs, compiler/noirc_frontend/src/parser/parser/attributes.rs, compiler/noirc_frontend/src/parser/parser/function.rs
This commit adds the parsing of formal verification attributes and their attachment to `FunctionDefinition` which is a structure and part of the AST which the Noir parser generates.
In this commit we also define a limit for the custom attributes. Their content body can not have formal verification attribute as a prefix.
Taking a look at the added unit tests may help with understanding the newly added feature.
=> feat(fv): add parsing for fv annotations

compiler/noirc_frontend/src/elaborator/mod.rs, compiler/noirc_frontend/src/elaborator/traits.rs, compiler/noirc_frontend/src/hir/comptime/interpreter.rs, compiler/noirc_frontend/src/hir_def/function.rs, test_programs/compile_failure/fv_attribute_name_resolution_1/Nargo.toml, test_programs/compile_failure/fv_attribute_name_resolution_1/src/main.nr, test_programs/compile_failure/fv_attribute_name_resolution_2/Nargo.toml, test_programs/compile_failure/fv_attribute_name_resolution_2/src/main.nr, test_programs/compile_failure/fv_attribute_name_resolution_3/Nargo.toml, test_programs/compile_failure/fv_attribute_name_resolution_3/src/main.nr, test_programs/compile_failure/fv_attribute_type_check_1/Nargo.toml, test_programs/compile_failure/fv_attribute_type_check_1/src/main.nr, test_programs/compile_failure/fv_attribute_type_check_2/Nargo.toml, test_programs/compile_failure/fv_attribute_type_check_2/src/main.nr, test_programs/compile_failure/fv_attribute_type_check_3/Nargo.toml, test_programs/compile_failure/fv_attribute_type_check_3/src/main.nr, test_programs/compile_success_empty/fv_attribute_name_resolution_1/Nargo.toml, test_programs/compile_success_empty/fv_attribute_name_resolution_1/src/main.nr, test_programs/compile_success_empty/fv_attribute_name_resolution_2/Nargo.toml, test_programs/compile_success_empty/fv_attribute_name_resolution_2/src/main.nr, test_programs/compile_success_empty/fv_attribute_name_resolution_3/Nargo.toml, test_programs/compile_success_empty/fv_attribute_name_resolution_3/src/main.nr, test_programs/compile_success_empty/fv_attribute_type_check_1/Nargo.toml, test_programs/compile_success_empty/fv_attribute_type_check_1/src/main.nr, test_programs/compile_success_empty/fv_attribute_type_check_2/Nargo.toml, test_programs/compile_success_empty/fv_attribute_type_check_2/src/main.nr, test_programs/compile_success_empty/fv_attribute_type_check_3/Nargo.toml, test_programs/compile_success_empty/fv_attribute_type_check_3/src/main.nr
Added name resolution and type checking for the expression bodies of the formal verification attributes. This means that functions in HIR now have resolved formal verification attributes attached to them.
Added tests which showcase the newly added functionality.
=> feat(fv): add semantic analysis for fv attributes

compiler/noirc_frontend/src/hir/mod.rs, tooling/nargo_cli/src/cli/fv_cmd.rs
Now if you run `nargo formal-verify` in a Noir workspace it will parse and do semantic analysis on all formal verification annotations. This happens only if the code can be compiled. Otherwise, it will throw compiler errors.
`nargo formal-verify` won't produce an output if the formal verification was successful.
=> feat(fv): connect `nargo formal-verify` to logic

flake.nix, shell.nix
Needed for @nickysn's work on tests and code coverage.
The `x86_64-unknown-linux-gnu` part from PATH will need to be changed for other architectures, but I don't know of any easy way to figure out this string, so for now I'll leave it as-is and will update in the future, if/when needed (any implementation > no implementation).
=> feat(shell.nix): Add llvm-tools binaries to path and add rustfilt package

Cargo.lock, derivation.nix, flake.nix, shell.nix, venir-toolchain.toml
Nix develop now packages the Venir project and adds it to $PATH.
This change should make it more seamless to the user that the Noir formal verification depends on the external binary Venir.
=> build(nix-shell): Nixify Venir

flake.lock, flake.nix, shell.nix, verusStd.nix
With this commit now we have nixified Verus std which means when we run direnv allow we will have vstd.vir locally available. This file contains the Verus standard library. Without it we wouldn't be able to formally verify arrays.
=> feat(nix): Nixify Verus std

compiler/noirc_evaluator/src/ssa/function_builder/mod.rs, compiler/noirc_evaluator/src/ssa/ir/dfg.rs, compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs, compiler/noirc_evaluator/src/ssa/ir/printer.rs, compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs, compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/mod.rs, compiler/noirc_frontend/src/monomorphization/mod.rs
Now we can formally verify code which has print functions in it.
Also run `cargo fmt`.
=> feat(fv): Ignore unconstrained print

compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/context.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/patterns.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/function.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/mod.rs, test_programs/formal_verify_failure/if_overflow/Nargo.toml, test_programs/formal_verify_failure/if_overflow/src/main.nr, test_programs/formal_verify_success/if_overflow_1/Nargo.toml, test_programs/formal_verify_success/if_overflow_1/src/main.nr, test_programs/formal_verify_success/if_overflow_2/Nargo.toml, test_programs/formal_verify_success/if_overflow_2/src/main.nr, test_programs/formal_verify_success/if_overflow_complex/Nargo.toml, test_programs/formal_verify_success/if_overflow_complex/src/main.nr
We had an issue where we would fail to verify correct Noir programs because we were directly translating the if optimization without taking into consideration the instruction `enable_side_effects_if`.
Now we take into consideration the instruction enable_side_effects_if. This way we are able to create `if` expressions which would be semantically equivalent to the ones in Noir's AST. Because we are generating VIR from SSA we have to reverse optimize some parts of the code which appears in the SSA.
Also added a few tests which show that we now properly translate if-else statements.
=> feat(fv): Change how we formally verify `ifs`

compiler/noirc_driver/src/lib.rs
`nargo fv --show-vir` will print the VIR we pass to Verus.
=> feat(fv): Add a switch to print the VIR to stdout

compiler/noirc_evaluator/src/ssa.rs, compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs, compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
With PR 130 we temporary broke `nargo execute` and `nargo prove`. With this commit we are applying a fix to the issue. Now `nargo execute` and `nargo prove` work like they used to.
All expected tests pass just like on the `formal-verification` branch.
=> fix(fv): Fix regression caused by #e89646

compiler/noirc_evaluator/src/ssa/ir/dfg.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/params.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/patterns.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/function.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/mod.rs
We now have attached the Noir Span into the VIR structure which we pass to Venir.
Unfortunately we had to encode the Noir Span into a string because of limitations related to the `RawSpan` structure.
In a later PR we will decode the Noir Span received from the Venir error reporting and we will report the error using the Noir compiler
=> feat(fv): First part of improving the error reporting

compiler/fm/src/file_map.rs, compiler/noirc_errors/src/reporter.rs, derivation.nix, tooling/nargo_cli/src/cli/fv_cmd.rs
Using the noirc tools for error reporting we have improved the output for the messages which we receive from the Verus back-end.
Also updated the derivation.nix file for Venir to be using the latest revision. This was done because Venir changed the way it outputs errors.
=> feat(fv): Better error reporting

tooling/nargo_cli/src/cli/fv_cmd.rs
Something which I forgot to do in the original commit for better error reporting.
=> fix(fv): Reverse the order for reporting errors

compiler/noirc_evaluator/src/ssa/ir/dfg.rs, compiler/noirc_evaluator/src/ssa/ir/instruction.rs, compiler/noirc_evaluator/src/ssa/opt/formal_verifications.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, test_programs/formal_verify_success/inline_functions_in_attributes/Nargo.toml, test_programs/formal_verify_success/inline_functions_in_attributes/src/main.nr, test_programs/formal_verify_success/inline_tuple_returning_func/Nargo.toml, test_programs/formal_verify_success/inline_tuple_returning_func/src/main.nr
With this pull request we now add the ability to call functions inside of formal verification attributes (ensures/requires). The way we do it is by inlining those function calls.
Added a test which show cases the newly added capabilities.
=> feat(fv): Inline functions in attributes

compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, test_programs/formal_verify_success/index_composite_array_with_const/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_const/src/main.nr, test_programs/formal_verify_success/index_composite_array_with_var_1/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_var_1/src/main.nr, test_programs/formal_verify_success/index_composite_array_with_var_2/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_var_2/src/main.nr, test_programs/formal_verify_success/index_composite_array_with_var_3/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_var_3/src/main.nr, test_programs/formal_verify_success/index_composite_array_with_var_4/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_var_4/src/main.nr, test_programs/formal_verify_success/index_composite_array_with_var_5/Nargo.toml, test_programs/formal_verify_success/index_composite_array_with_var_5/src/main.nr
Added logic for properly indexing the flattened SSA arrays.
Noir SSA flattens arrays which are made of composite types (tuples, structs, arrays). This resulted in having heterogeneous arrays which can not be converted directly to Verus.
What we did to fix it is that we unflattened the array by making the inner type a tuple. We also added a special logic for calculating the index for the unflattened array and the index for the tuple.
Added tests which show off the new capabilities.
=> feat(fv): Index arrays made of composite types

compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs, compiler/noirc_frontend/src/ast/expression.rs, compiler/noirc_frontend/src/ast/mod.rs, compiler/noirc_frontend/src/elaborator/types.rs, compiler/noirc_frontend/src/hir/comptime/display.rs, compiler/noirc_frontend/src/hir/comptime/interpreter.rs, compiler/noirc_frontend/src/lexer/lexer.rs, compiler/noirc_frontend/src/lexer/token.rs, compiler/noirc_frontend/src/parser/mod.rs, compiler/noirc_frontend/src/parser/parser.rs, test_programs/formal_verify_failure/implication_operator/Nargo.toml, test_programs/formal_verify_failure/implication_operator/src/main.nr, test_programs/formal_verify_success/implication_operator_1/Nargo.toml, test_programs/formal_verify_success/implication_operator_1/src/main.nr, test_programs/formal_verify_success/implication_operator_2/Nargo.toml, test_programs/formal_verify_success/implication_operator_2/src/main.nr
For writing more readable proofs we need the implication operator. With this commit we now add it. The user can write x ==> y where x and y are boolean statements.
We are transforming the implication operator into !x | y which is logically equivalent to x ==> y.
The implication operator can be used both in attributes and function's bodies.
Added tests which showcase the new feature.
=> feat(fv): Add the implication operator

Cargo.lock, flake.nix, noir.nix
Create `noir.nix` file for the Noir derivation definition.
Set Noir as default package in the flake.
=> feat(nix): Nixify Noir

compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, test_programs/formal_verify_failure/array_set_composite_types_1/Nargo.toml, test_programs/formal_verify_failure/array_set_composite_types_1/src/main.nr, test_programs/formal_verify_success/array_set_1/Nargo.toml, test_programs/formal_verify_success/array_set_1/src/main.nr
With this pull request we now add the ability to formally verify code which contains array mutating instructions. For now you can only mutate arrays of primitive types but soon we will add the possibility for mutating all types of arrays.
I expect there to be conflicts when rebasing this branch after PR #138 has been merged into `formal-verification`. That's why I opened this PR as draft.
=> feat(fv): Support for mutating arrays made of primitive types

compiler/noirc_frontend/src/ast/expression.rs, compiler/noirc_frontend/src/ast/visitor.rs, compiler/noirc_frontend/src/elaborator/expressions.rs, compiler/noirc_frontend/src/hir/comptime/display.rs, compiler/noirc_frontend/src/lexer/lexer.rs, compiler/noirc_frontend/src/lexer/token.rs, compiler/noirc_frontend/src/parser/parser.rs, test_programs/formal_verify_failure/exists_big_element_sum/Nargo.toml, test_programs/formal_verify_failure/exists_big_element_sum/src/main.nr, test_programs/formal_verify_failure/exists_zero_in_array/Nargo.toml, test_programs/formal_verify_failure/exists_zero_in_array/src/main.nr, test_programs/formal_verify_failure/forall_max_is_max/Nargo.toml, test_programs/formal_verify_failure/forall_max_is_max/src/main.nr, test_programs/formal_verify_failure/forall_sum_of_evens/Nargo.toml, test_programs/formal_verify_failure/forall_sum_of_evens/src/main.nr, tooling/lsp/src/requests/completion/builtins.rs, tooling/lsp/src/requests/inlay_hint.rs, tooling/nargo_fmt/src/rewrite/expr.rs
We can now parse quantifier expressions.
Added unit tests which show off the new capabilities of the parser.
=> feat(fv): Parse quantifier expressions

formal_verification_docs/src/getting_started.md
Some steps were missing for non Nix macines.
=> docs(fv): Update build guide

tooling/tracer/src/tracer_glue.rs
part of small cleanup of our logging/printed messages
Resolves 
Check one:
=> cleanup: shorten the "saved trace" message to one line; fix error for paths

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs, test_programs/formal_verify_success/load_store_instructions/Nargo.toml, test_programs/formal_verify_success/load_store_instructions/src/main.nr
Before this fix the newly added test was generating incorrect load instruction inside of the require annotation body.
With the added patch we now correct the load instruction to load the proper value. This is being done during the mem2reg optimization where store and load instructions are being optimized away. It's a convinient place where we can do this optimization.
=> fix(fv): Fix incorrect load instructions in annotations

tooling/nargo_cli/build.rs
This was a slight regression due to
https://github.com/blocksense-network/noir/pull/194.
=> fix(build): cargo test succeeds again

compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs, test_programs/formal_verify_success/is_sorted_no_quant/Nargo.toml, test_programs/formal_verify_success/is_sorted_no_quant/src/main.nr
More details on the bug and how it was fixed can be found in the commit description.
Added a test which has a function which generates SSA with a last instruction `store`.
=> fix(fv): Fix inlining of function which have `store` as a last instructions

compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/types.rs
We were previously mapping the Field type to unsigned 254 bit integer type which was incorrect.
=> fix(fv): Map Field type to signed 254 bits

compiler/noirc_evaluator/src/ssa/verus_vir_gen/context.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs, compiler/noirc_evaluator/src/ssa/verus_vir_gen/function.rs, test_programs/formal_verify_success/array_let_var_in_trigger/Nargo.toml, test_programs/formal_verify_success/array_let_var_in_trigger/src/main.nr
In a previous fix we didn't consider the possibility of arrays being a let defined variables. We now have handled this case.
Also previously we had missed a corner case for the recursion. If you encounter one of the return parameters of the function you would want the recursion to end.
Now we add the return value ids of a function to recursion bottom set.
=> fix(fv): Remove let array vars from triggers

formal_verification_docs/src/SUMMARY.md, formal_verification_docs/src/blocksense_noir.md, formal_verification_docs/src/noir_tracer/README.md, formal_verification_docs/src/noir_tracer/debugging_with_codetracer.md
Added an introduction page. Also we now mention CodeTracer. Added "Debugging with CodeTracer" header in the Noir Tracer page.
=> docs(noir): Add introduction page and information about CT

compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs
Before we wrapping the `lt` instruction with an `if` expression if it was located inside of an `enable side_effects` block.
This was not needed because `lt` is not a dangerous instruction.
It also caused crashes in the case of `v21 = lt v20 v5` because `v21` is of type `bool` and the default value for the `else` clause of the `if` wrapper was of a type `Int`.
=> fix(fv): Do not wrap with `if` `lt` instructions

compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/types.rs
In #203 we missed out on correcting some functions which translate the Noir Field type to a VIR type.
=> fix(fv): Correct type translation for Field

test_programs/formal_verify_failure/field_type_limit/Nargo.toml, test_programs/formal_verify_failure/field_type_limit/src/main.nr, test_programs/formal_verify_failure/field_type_limit_2/Nargo.toml, test_programs/formal_verify_failure/field_type_limit_2/src/main.nr, test_programs/formal_verify_success/cast_to_avoid_field/Nargo.toml, test_programs/formal_verify_success/cast_to_avoid_field/src/main.nr
Added tests which do basic arithmetic operation with a variable of type `Field`. They fail to verify successfully because Verus does not support logical reasoning for integer types with a bit size different from `8`, `16`, `32`, `64`, `128`.
The default Noir `Field` is of bit size `254`.
Added a test which shows that casting from Field to another type and then doing the mathematical operation is verified successfully.
We have opened an issue in Verus asking if they are actually planning a support for odd int types.
https://github.com/verus-lang/verus/issues/1503
=> test(fv): Formal verification limit for Field type

Cargo.lock, acvm-repo/blackbox_solver/Cargo.toml
This is a blocker for the CodeTracer team and their goal to make Noir compatible for Windows OS.
With upgrading the version of blake3 from 1.6.0 to 1.7.0 this is issue is resolved.
=> chore(acvm): Bump blake3 version to 1.7.0

Cargo.lock, tooling/artifact_cli/Cargo.toml, tooling/artifact_cli/src/errors.rs, tooling/nargo_cli/src/cli/fs/inputs.rs, tooling/nargo_cli/src/cli/fs/mod.rs, tooling/nargo_cli/src/cli/fs/proof.rs, tooling/nargo_cli/src/errors.rs
This commit clears some technical debt which we had acquired during our daily syncs. Upstream have moved the type `FilesystemError` into a different file and also made it a part of the type `CliError`.
We made our code compatible with those changes.
=> chore(errors): Remove deprecated `FilesystemError`

compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs, compiler/noirc_frontend/src/ast/expression.rs, compiler/noirc_frontend/src/ast/mod.rs, compiler/noirc_frontend/src/hir/comptime/interpreter/infix.rs, compiler/noirc_frontend/src/parser/parser/expression.rs, compiler/noirc_frontend/src/parser/parser/infix.rs
Also expanded the AST expression structure to support implication operator. This is different than the prototype implementation where when we parsed an implication `p ==> q` we transformed it into `!p | q`.
This means that we will have to constrain its use only spec code in a
separate commit. Just the same way we will do with the quantifier expressions.
Another option is to not accept this PR and implement the parser the same way we did in the prototype. We will discuss which option is more upstream friendly.
=> feat(fv): Parser for implication operator

test_programs/formal_verify_failure/fv_attribute_name_resolution_1/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_name_resolution_1/src/main.nr, test_programs/formal_verify_failure/fv_attribute_name_resolution_2/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_name_resolution_2/src/main.nr, test_programs/formal_verify_failure/fv_attribute_name_resolution_3/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_name_resolution_3/src/main.nr, test_programs/formal_verify_failure/fv_attribute_type_check_1/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_type_check_1/src/main.nr, test_programs/formal_verify_failure/fv_attribute_type_check_2/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_type_check_2/src/main.nr, test_programs/formal_verify_failure/fv_attribute_type_check_3/Nargo.toml, test_programs/formal_verify_failure/fv_attribute_type_check_3/src/main.nr, tooling/nargo_cli/build.rs
Now there are two directories for testing formal verification functionality. Them being `formal_verify_failure` and `formal_verify_success`.
Added some tests which check if the semantic analysis of fv annotation expressions is correct.
=> test(fv): Expand testing logic

compiler/noirc_frontend/src/elaborator/expressions.rs, compiler/noirc_frontend/src/elaborator/lints.rs, compiler/noirc_frontend/src/elaborator/mod.rs, compiler/noirc_frontend/src/hir/comptime/errors.rs, compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs, compiler/noirc_frontend/src/hir/comptime/interpreter.rs, compiler/noirc_frontend/src/hir/resolution/errors.rs, compiler/noirc_frontend/src/hir_def/expr.rs, compiler/noirc_frontend/src/monomorphization/mod.rs
Added type checking and name resolution for quantifier expressions. This happens during the elaboration phase in the Noir compiler.
Because of a limitation of the Noir type system we initialize the quantifier indexes with type `Unbounded(Any)`. Those types automatically bound themseleves to the first type they interact with. In result the user sometimes has to do some extra type casting when using indexes.
=> feat(fv): Semantic analysis for quantifiers

compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs, compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs, compiler/noirc_frontend/src/ast/expression.rs, compiler/noirc_frontend/src/elaborator/types.rs, compiler/noirc_frontend/src/hir/type_check/errors.rs, compiler/noirc_frontend/src/node_interner.rs, noir_stdlib/src/ops/bit.nr
Added special type checking for the implication operator. Both lhs and rhs must be of type bool.
During the SSA gen phase the implication operation `p ==> q` is being transformed to `!p | q`.
=> feat(fv): Semantic analysis for implication operator

Cargo.lock, Cargo.toml
The verus-lib dependency will have major changes to it. Therefore we want to lock onto the last stable version.
=> chore(vir): Lock vir dependency version

compiler/noirc_evaluator/src/vir/vir_gen/attribute.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/mod.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/params.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/types.rs, compiler/noirc_evaluator/src/vir/vir_gen/function.rs, compiler/noirc_evaluator/src/vir/vir_gen/mod.rs
This PR is a step towards of having a minimally verifiable Noir program. Not all expressions have been translated from monomorphized AST to VIR. The remaining TODOs will be implemented in later PRs.
Next step is to integrate Venir and pass the generated VIR to it.
=> feat(ast-to-vir): Minimal implementation for mapping AST to VIR 

compiler/noirc_evaluator/src/vir/vir_gen/attribute.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/types.rs, compiler/noirc_frontend/src/monomorphization/mod.rs
Convert pre/post-conditions from AST to VIR.
Also we are now using the proper ids when we are converting AST identifiers to VIR.
No tests have been added to this PR because some issues were discovered with the variable `result`.
=> feat(ast-to-vir): Convert FV annotations to VIR

compiler/noirc_evaluator/src/vir/opt_passes/loop_unroll.rs, compiler/noirc_evaluator/src/vir/opt_passes/mod.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/mod.rs, test_programs/formal_verify_success/for_loop_array_const/Nargo.toml, test_programs/formal_verify_success/for_loop_array_const/src/main.nr, test_programs/formal_verify_success/for_loop_blocks/Nargo.toml, test_programs/formal_verify_success/for_loop_blocks/src/main.nr, test_programs/formal_verify_success/for_loop_nested_complex/Nargo.toml, test_programs/formal_verify_success/for_loop_nested_complex/src/main.nr, test_programs/formal_verify_success/for_loop_nested_simple/Nargo.toml, test_programs/formal_verify_success/for_loop_nested_simple/src/main.nr, test_programs/formal_verify_success/for_loop_simple/Nargo.toml, test_programs/formal_verify_success/for_loop_simple/src/main.nr, test_programs/formal_verify_success/for_loop_structure_const/Nargo.toml, test_programs/formal_verify_success/for_loop_structure_const/src/main.nr, test_programs/formal_verify_success/for_loop_tuple_const/Nargo.toml, test_programs/formal_verify_success/for_loop_tuple_const/src/main.nr
Implemented the optimization pass which unrolls `for` loops.
Currently due to the lack of constants propagation pass we can not unroll all possible `for` loops. If we have a variable which depends on the result of a function call we don't have the required context to evaluate if the function call returns a constant.
Added multiple tests which show off the newly added feature.
=> feat(ast-passes): `for` loop unrolling

compiler/noirc_frontend/src/elaborator/mod.rs, compiler/noirc_frontend/src/monomorphization/ast.rs, compiler/noirc_frontend/src/monomorphization/printer.rs, test_programs/formal_verify_success/exists_big_element_sum/Nargo.toml, test_programs/formal_verify_success/exists_big_element_sum/src/main.nr, test_programs/formal_verify_success/exists_zero_in_array/Nargo.toml, test_programs/formal_verify_success/exists_zero_in_array/src/main.nr, test_programs/formal_verify_success/forall_max_is_max/Nargo.toml, test_programs/formal_verify_success/forall_max_is_max/src/main.nr, test_programs/formal_verify_success/forall_structure/Nargo.toml, test_programs/formal_verify_success/forall_structure/src/main.nr, test_programs/formal_verify_success/forall_sum_of_evens/Nargo.toml, test_programs/formal_verify_success/forall_sum_of_evens/src/main.nr
We now enable the specification context flag while elaborating FV annotations. If this flag is set to `false` we produce errors when we encounter quantifiers.
Removed an old `todo!()` which was forgotten.
Specified that the return type of a quantifier expression is boolean.
Added multiple tests which previously didn't pass because of aforementioned bugs.
=> fix(quantifiers): Fix quantifier bugs

compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/types.rs
We now convert `reference` and `dereference` operators to VIR.
The derefence operator is being ignored because this is how Verus operates with dereferences.
=> feat(ast-to-vir): Reference support

compiler/noirc_evaluator/src/vir/opt_passes/mod.rs, compiler/noirc_evaluator/src/vir/opt_passes/mut_args.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs, compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/params.rs, test_programs/formal_verify_success/call_struct_method/Nargo.toml, test_programs/formal_verify_success/call_struct_method/src/main.nr, test_programs/formal_verify_success/fv_std_old/Nargo.toml, test_programs/formal_verify_success/fv_std_old/src/main.nr, test_programs/formal_verify_success/mutate_array_of_tuples/Nargo.toml, test_programs/formal_verify_success/mutate_array_of_tuples/src/main.nr
Verus performs a transformation on function parameters where mutable arguments are converted into immutable ones, and a `let` mut binding is inserted at the beginning of the function body. To stay consistent with this behavior, we apply the same transformation during our monomorphized AST passes.
Added a test which shows off how the function `old()` from `fv_std` lib works.
Added two more tests which previously didn't pass.
=> fix(mut-args): Convert mut args to non mut
