blocksense-network/noir

- .envrc
- .gitignore
- Cargo.lock
- flake.lock
- flake.nix
- shell.nix
- tooling/acvm_cli/Cargo.toml
- tooling/nargo_cli/Cargo.toml
This is an attempt to share my local shell.nix which installs rustup.
I got it from here: https://nixos.wiki/wiki/Rust#Installation_via_rustup
Nix instructions: https://coda.io/d/Metacraft-Labs-Wiki_db0u3vDsy39/Nix-Devshells_suHgW?searchClick=c0adf925-91d4-4fcf-8437-172565dbd833_b0u3vDsy39#_lu-La
> feat: Add Nix config that installs rustup

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
The actual logic behind printing the PLONKY2 circuit isn't implemented, yet.
> feat(plonky2): Added command line option '--show-plonky2'

- compiler/noirc_evaluator/src/ssa/plonky2_gen/asm_writer.rs
- compiler/noirc_evaluator/src/ssa/plonky2_gen/console_asm_writer.rs
- compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
This adds '--show-plonky2' support for the following plonky2 calls:
register_public_inputs
add_many
le_sum
range_check
> feat(plonky2): Print more plonky2 calls with '--show-plonky2'

- tooling/tracer/src/lib.rs
This commit just outlines some logic into the
`get_current_line_and_filepath` function, to keep the body of
`step_debugger` fitting on a single screen.
Also, a long TODO comment is replaced with a reference to a filed bug.
There is no functional change: the test still passes:
```
cargo test plonky2_trace
```
> feat(tracing): Outline `get_current_line_and_filepath`

- tooling/tracer/src/lib.rs
Changes:
* a `SourceLocation` struct is introduced to handle a file-line pair in a more hygienic way
* a `DebugStepResult` is introduced, to simplify the interface between `trace_circuit` and `step_debugger`
Run the tracing tests to see that they still pass:
```
cargo test trace
```
There is no change in the tests, which demonstrates that there's no change in the business logic. This is just a structural change.
> feat(trace): introduce SourceLocation and DebugStepResult

- README.md
Recently, I removed some information that I thought too low-level for the README. I am bringing some of it back, after discussing with @zah that people might find it useful.
> docs(README.md): explain pipeline fork

- .envrc
- scripts/bin/nargo
> Implement nargo alias

- test_programs/plonky2_trace/1_mul/expected_metadata.json
- test_programs/plonky2_trace/2_function_calls/expected_metadata.json
- test_programs/plonky2_trace/3_two_files/expected_metadata.json
- tooling/nargo_cli/build.rs
- tooling/nargo_cli/src/cli/trace_cmd.rs
A simple yet effective change.
> feat(tracer): Store package name in trace metadata

- flake.nix
- shell.nix
Fixes the problem with the rust enviornment not loading properly, specifically the rust-analyzer tool.
Co-authored-by: Petar Kirov <petar@metacraft-labs.com>
> chore(nix): Fix the rust-analyzer issue

- compiler/noirc_evaluator/src/ssa/plonky2_gen/mod.rs
This is preparation for the support of signed integers. No functional changes.
> feat(plonky2): introduced a "signed" boolean flag to P2Type::Integer

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ir/dfg.rs
- compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/ir/printer.rs
- compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- compiler/noirc_frontend/src/monomorphization/ast.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
The code compiles, however it needs to be tested.
> feat: Formal Verification attributes inside the SSA

- compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs
We forgot to wrap the array get instruction with a VIR if. This resulted in false positives from the formal verifier.
Now it has been fixed the same way we did for binaries
> feat(fv): Make array get in ifs work

- compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs
Before this commit the call instruction in the FF attributes's SSA was being transformed into an invalid call instruction which has a numeric constant as an argument.
To fix this we made the "Defunctionalize" optimization to also process the formal verification SSA instructions.
All tests pass locally.
> fix(fv): Fix function calls in attributes's SSA

- tooling/nargo_cli/src/main.rs
> config(panic): Point to Blocksense repo, not upstream

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/monomorphization/ast.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/monomorphization/printer.rs
Implemented the logic which converts the quantifier expressions from HIR AST to Monomorphed AST.
> feat(fv): Monomorphize quantifier expression

- compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs
We are generating allocate instructions for the quantifier indexes. Those instructions are now ignored when we reach the SSA to VIR phase because they are not needed. Their only purpose is to help generate the quantifier body expression with the correct value ids.
> chore(fv): Ignore quantifier allocate instructions

- README.md
-fixed a few grammatical errors.
-corrected the spelling of "barretenberg" (it was misspelled as "barratenberg" and "barrentenberg" in a few places)
Resolves 
Check one:
> fix: grammar and spelling issues

- compiler/noirc_frontend/src/monomorphization/mod.rs
We now support multiple attributes but with limited error reporting. This is the case because if we wanted to have better error reporting we would have to do some major code refactoring.
Better multiple attributes support is being postponed for the future.
> feat(fv): Support multiple attributes

- formal_verification_docs/src/SUMMARY.md
- formal_verification_docs/src/annotations/README.md
- formal_verification_docs/src/annotations/attributes.md
- formal_verification_docs/src/annotations/pre_and_postconditions.md
Added documentation for `ensures` and `requires` attributes.
> docs(fv): Attributes page

- formal_verification_docs/src/specs_grammar.md
This page contains information about our expansion of the Noir grammar. It also mentions some specific details about our Formal Verificaiton System which are not common among other FVS.
> docs(fv): Specifications syntax page

- tooling/nargo_cli/src/cli/fv_cmd.rs
This will make the error reporting more intuitive to follow.
> chore(fv): Sort errors by Span

- test_programs/formal_verify_success/binary_search_v1/Nargo.toml
- test_programs/formal_verify_success/binary_search_v1/src/main.nr
Added a **formally verified** binary search program which works with arrays of 30 elements. Because of implementation details we can not support bigger arrays because the verification times out.
We will soon add a better implementation of binary search which avoids those limits.
> test(fv): Binary search V1

- test_programs/formal_verify_success/binary_search_v2/Nargo.toml
- test_programs/formal_verify_success/binary_search_v2/src/main.nr
Rewrote binary search V1 with the goal of not using an `if` expression in the `for` loop body. Also slightly improved the function for the binary search step in. It no longer has potential to underflow therefore the proof is a bit shorter.
In result the binary search works with 200 element array and it takes 2 seconds to verify the program.
> test(fv): Binary search V2

- compiler/noirc_evaluator/src/ssa/verus_vir_gen/attributes.rs
- compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/exprs.rs
- compiler/noirc_evaluator/src/ssa/verus_vir_gen/expr_to_vir/patterns.rs
- compiler/noirc_evaluator/src/ssa/verus_vir_gen/function.rs
- compiler/noirc_evaluator/src/ssa/verus_vir_gen/mod.rs
- compiler/noirc_frontend/src/ast/expression.rs
- tooling/nargo_cli/src/cli/fv_cmd.rs
Added and updated comments in code related to formal verification logic.
> chore(fv): Update comments

- tooling/nargo_cli/src/cli/fv_cmd.rs
Added the ability to propagate flags to the Venir backend. Example of a useful flag that a user may want to propagate is `--rlimit=n`. It is used for extending the time which the Verus backend computes before timing out.
> feat(fv): Propagate flags to Venir backend

- Cargo.lock
- Cargo.toml
- compiler/noirc_driver/src/lib.rs
- compiler/noirc_driver/src/program.rs
- compiler/noirc_evaluator/src/vir/mod.rs
- compiler/noirc_evaluator/src/vir/vir_gen/attribute.rs
- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs
- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/mod.rs
- compiler/noirc_evaluator/src/vir/vir_gen/function.rs
- compiler/noirc_evaluator/src/vir/vir_gen/mod.rs
Scaffold modules and functions which will be implemented in upcoming commits.
> chore(fv): Set up VIR gen module

- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs
- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/mod.rs
- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/params.rs
- compiler/noirc_evaluator/src/vir/vir_gen/function.rs
- test_programs/formal_verify_success/safe_division/Nargo.toml
- test_programs/formal_verify_success/safe_division/src/main.nr
This PR includes fixes that allow our first simple test to pass.
> feat(fv): First working FV test 

- compiler/noirc_evaluator/src/vir/vir_gen/expr_to_vir/expr.rs
This commit adds support for processing `Clone` and `Drop` expressions introduced by the `handle_ownership` pass in unconstrained Noir code.
- `Clone` expressions are treated as no-ops in Verus. Since arrays in Rust implement the `Copy` trait, we simply return the inner expression and ignore the clone.
- `Drop` expressions, which decrement reference counts in Noir, are unsupported in Verus. We consume the inner expression and return a unit expression instead.
> feat(ast-to-vir): Support for `Clone` and `Drop` expressions

- Cargo.lock
- Cargo.toml
- compiler/formal_verification/src/parse/mod.rs
- compiler/fv_bridge/Cargo.toml
- compiler/fv_bridge/src/lib.rs
- compiler/noirc_evaluator/Cargo.toml
- compiler/noirc_evaluator/src/vir/mod.rs
- compiler/noirc_evaluator/src/vir/vir_gen/function.rs
- compiler/noirc_evaluator/src/vir/vir_gen/mod.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- tooling/nargo_cli/Cargo.toml
- tooling/nargo_cli/src/cli/fv_cmd.rs
Instead of extending the Noir AST with our own attributes we will be using Tag attributes.
> feat(syntax)!: New syntax for formal verification annotations
